name: "Release Pipeline"
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: prepare
      run: npm install @semantic-release/github @semantic-release/exec conventional-changelog-conventionalcommits

    - name: release
      run: npx semantic-release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: set version
      run: echo "version=$(cat version)" >> $GITHUB_ENV

    - name: build docker image
      run: |
        echo "X=$(echo $version | awk -F . '{print $1}')" >> $GITHUB_ENV
        echo "XY=$(echo $version | awk -F . '{print $1"."$2}')" >> $GITHUB_ENV
        echo "XYZ=$(echo $version)" >> $GITHUB_ENV
        echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker build -t ${{ github.repository }}:latest -t ghcr.io/${{ github.repository }}:latest --build-arg version=$version .

    - name: publish docker image (dockerhub)
      run: |
        docker tag ${{ github.repository }}:latest ${{ github.repository }}:$X
        docker tag ${{ github.repository }}:latest ${{ github.repository }}:$XY
        docker tag ${{ github.repository }}:latest ${{ github.repository }}:$XYZ
        docker push ${{ github.repository }}:latest
        docker push ${{ github.repository }}:$X
        docker push ${{ github.repository }}:$XY
        docker push ${{ github.repository }}:$XYZ

    - name: publish docker image (ghcr)
      run: |
        docker tag ghcr.io/${{ github.repository }}:latest ghcr.io/${{ github.repository }}:$X
        docker tag ghcr.io/${{ github.repository }}:latest ghcr.io/${{ github.repository }}:$XY
        docker tag ghcr.io/${{ github.repository }}:latest ghcr.io/${{ github.repository }}:$XYZ
        docker push ghcr.io/${{ github.repository }}:latest
        docker push ghcr.io/${{ github.repository }}:$X
        docker push ghcr.io/${{ github.repository }}:$XY
        docker push ghcr.io/${{ github.repository }}:$XYZ
