name: "Release Pipeline"
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: prepare
      run: npm install @semantic-release/github @semantic-release/exec conventional-changelog-conventionalcommits

    - name: release
      run: npx semantic-release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: set version
      run: echo "version=$(cat version)" >> $GITHUB_ENV

    - name: publish docker image
      run: |
        echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        echo ${{ secrets.DOCKER_TOKEN }} | docker login -u $DOCKER_USERNAME --password-stdin
        docker build -t ghcr.io/${{ github.repository }}:$version -t ${{ github.repository }}:$version -t ghcr.io/${{ github.repository }}:latest -t ${{ github.repository }}:latest .
        docker push ghcr.io/${{ github.repository }}:$version
        docker push ${{ github.repository }}:$version
        docker push ghcr.io/${{ github.repository }}:latest
        docker push ${{ github.repository }}:latest